theme: jekyll-theme-minimal
title: EasyPlanner
description: EasyPlanner adalah aplikasi manajemen waktu yang canggih yang memungkinkan pengguna untuk dengan mudah mengelola jadwal harian melalui UI dan UX yang mulus.
